version: "3.7"

services:   
  basicrum_clickhouse_server_build:
    image: clickhouse/clickhouse-server:22.8
    volumes:
      - ./clickhouse/data:/var/lib/clickhouse
      - ./clickhouse/users.d/:/etc/clickhouse-server/users.d/
      - ./clickhouse/start-data/:/start-data/

    ulimits:
      nproc: 65535
      nofile:
       soft: 262144
       hard: 262144

  basicrum_grafana_quicktest:
    build: .
    # We need this in order to make the grafana container happy when we have volumes.
    # If we don't set the user then we get:
    # --------------------------------------------------------------------------------------------------------
    # basicrum_grafana_1            | GF_PATHS_DATA='/var/lib/grafana' is not writable.
    # basicrum_grafana_1            | You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migrate-to-v51-or-later
    # basicrum_grafana_1            | mkdir: cannot create directory '/var/lib/grafana/plugins': Permission denied
    # --------------------------------------------------------------------------------------------------------
    # 
    # $UID is passed by the host: 
    #
    # 1.| UID := $(shell id -u)
    # 2.| env UID=${UID} docker-compose -f ${dc_path} up -d
    # 
    user: "$UID"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
    ports:
      - 3300:3000
    volumes:
      # Mount provisioning related stuff
      - ./build/datasources:/etc/grafana/provisioning/datasources
      - ./build/dashboards:/etc/grafana/provisioning/dashboards