version: "3.7"

services:   
  basicrum_grafana_build:
    build: .
    ports:
      - 3300:3000
    env_file:
      - .env
    volumes:
      - ./build/datasources:/etc/grafana/provisioning/datasources
      - ./build/dashboards:/etc/grafana/provisioning/dashboards

  basicrum_clickhouse_server_build:
    image: clickhouse/clickhouse-server:22.8
    env_file:
      - .env
    volumes:
      - ./clickhouse/data:/var/lib/clickhouse
      - ./setup/ch/users.d:/etc/clickhouse-server/users.d
      - ./setup/ch/init-schema:/docker-entrypoint-initdb.d

    ulimits:
      nproc: 65535
      nofile:
       soft: 262144
       hard: 262144
