version: "3.7"

services:
  basicrum_grafana_standalone:
    build: .
    # We need this in order to make the grafana container happy when we have volumes.
    # If we don't set the user then we get:
    # --------------------------------------------------------------------------------------------------------
    # basicrum_grafana_1            | GF_PATHS_DATA='/var/lib/grafana' is not writable.
    # basicrum_grafana_1            | You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migrate-to-v51-or-later
    # basicrum_grafana_1            | mkdir: cannot create directory '/var/lib/grafana/plugins': Permission denied
    # --------------------------------------------------------------------------------------------------------
    # 
    # $UID is passed by the host: 
    #
    # 1.| UID := $(shell id -u)
    # 2.| env UID=${UID} docker-compose -f ${dc_path} up -d
    # 
    user: "$UID"
    ports:
      - 3300:3000
    volumes:
      # Mount provisioning related stuff
      - ./build/datasources:/etc/grafana/provisioning/datasources
      - ./build/dashboards:/etc/grafana/provisioning/dashboards