version: "3.7"

services:   
  basicrum_grafana_build:
    build: .
    ports:
      - 3200:3000
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_CONNECTION_URL: ${CLICKHOUSE_CONNECTION_URL}
      CLICKHOUSE_CONNECTION_PORT:  ${CLICKHOUSE_CONNECTION_PORT}

  basicrum_clickhouse_server_build:
    image: clickhouse/clickhouse-server:22.8
    volumes:
      - ./clickhouse/data:/var/lib/clickhouse
      - ./clickhouse/users.d/:/etc/clickhouse-server/users.d/

    ulimits:
      nproc: 65535
      nofile:
       soft: 262144
       hard: 262144
