{
 "title": "Summary",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Host",
    "query": "SELECT hostname AS __text, concat('\\'', hostname, '\\'')  AS __value FROM webperf_rum_events where  hostname NOT LIKE  '%.goog' AND hostname != ''  group by hostname"
   }
  ]
 },
 "panels": [
  {
   "title": "Visits per day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "created_at",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    toDate(event_date) as t,\n    countIf(device_type = 'mobile') as Mobile,\n    countIf(device_type = 'desktop') as Desktop\nFROM $table\n\nWHERE\n    $timeFilter\n\n    AND event_type = 'visit_page'\n    $conditionalTest(AND hostname in($hostname), $hostname)\n\nGROUP BY t\nORDER BY t\n",
     "rawQuery": "SELECT\n    toDate(event_date) as t,\n    countIf(device_type = 'mobile') as Mobile,\n    countIf(device_type = 'desktop') as Desktop\nFROM default.webperf_rum_events\n\nWHERE\n    event_date >= toDate(1666184329) AND event_date <= toDate(1668779929) AND created_at >= toDateTime(1666184329) AND created_at <= toDateTime(1668779929)\n\n    AND event_type = 'visit_page'\n     AND hostname in('skyrecord.eu') \n\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "table": "webperf_rum_events"
    }
   ]
  },
  {
   "title": "Screen Widths",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "created_at",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    intDiv(screen_width, 100) * 100 as screen_width,\n    sum(toUInt64(1)) as count\n    \nFROM $table\n\nWHERE\n    $timeFilter\n    AND event_type = 'visit_page'\n    AND screen_width <= 2500\n    $conditionalTest(AND hostname in($hostname), $hostname)\n\nGROUP BY screen_width\nORDER BY screen_width\n\n",
     "rawQuery": "SELECT\n    intDiv(screen_width, 150) * 150 as screen_width,\n    sum(toUInt64(1)) as count\n    \nFROM default.webperf_rum_events\n\nWHERE\n    event_date >= toDate(1660563602) AND event_date <= toDate(1668343202) AND created_at >= toDateTime(1660563602) AND created_at <= toDateTime(1668343202)\n    AND event_type = 'visit_page'\n    AND screen_width <= 2500\n     AND hostname in('iventishirts1.com') \n\nGROUP BY screen_width\nORDER BY screen_width",
     "round": "0s",
     "table": "webperf_rum_events"
    }
   ]
  },
  {
   "title": "Device distribution",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "created_at",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    toDate(event_date) as t,\n    countIf(device_type = 'desktop') as desktop,\n    countIf(device_type = 'tablet') as tablet,\n    countIf(device_type = 'mobile') as mobile,\n    countIf(device_type = 'bot') as bot\n\nFROM $table\n\nWHERE t BETWEEN toDateTime($from) AND toDateTime($to)\n    AND event_type = 'visit_page'\n    $conditionalTest(AND hostname in($hostname), $hostname)\nGROUP BY t",
     "rawQuery": "SELECT\n    toDate(event_date) as t,\n    countIf(device_type = 'desktop') as desktop,\n    countIf(device_type = 'tablet') as tablet,\n    countIf(device_type = 'mobile') as mobile,\n    countIf(device_type = 'bot') as bot\n\nFROM default.webperf_rum_events\n\nWHERE t BETWEEN toDateTime(1666184253) AND toDateTime(1668779853)\n    AND event_type = 'visit_page'\n     AND hostname in('skyrecord.eu') \nGROUP BY t",
     "round": "0s",
     "table": "webperf_rum_events"
    }
   ]
  },
  {
   "title": "OS Distribution PLACEHOLDER",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": {
    "content": "# Title\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)"
   }
  },
  { "title": "Business metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Bounce rate - All",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "created_at",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \n    event_date,\n    bounce_rate\nFROM (\n  SELECT\n      event_date,\n      count() AS all_sessions,\n      countIf(max_length = 1) AS bounced_sessions,\n      ((bounced_sessions / all_sessions) * 100) as bounce_rate\n  FROM\n  (\n      SELECT\n          event_date,\n          session_id,\n          max(session_length) AS max_length\n      FROM $table\n      WHERE \n        $timeFilter\n        AND event_type = 'visit_page'\n        AND visibility_state = 'visible'\n        AND device_type IN ('mobile','desktop','tablet')\n        $conditionalTest(AND hostname in($hostname), $hostname)\n      GROUP BY event_date, session_id\n  )\n  GROUP BY event_date\n)\n",
     "rawQuery": "SELECT \n    event_date,\n    bounce_rate\nFROM (\n  SELECT\n      event_date,\n      count() AS all_sessions,\n      countIf(max_length = 1) AS bounced_sessions,\n      ((bounced_sessions / all_sessions) * 100) as bounce_rate\n  FROM\n  (\n      SELECT\n          event_date,\n          session_id,\n          max(session_length) AS max_length\n      FROM default.webperf_rum_events\n      WHERE \n        event_date >= toDate(1666184714) AND event_date <= toDate(1668780314) AND created_at >= toDateTime(1666184714) AND created_at <= toDateTime(1668780314)\n        AND event_type = 'visit_page'\n        AND visibility_state = 'visible'\n        AND device_type IN ('mobile','desktop','tablet')\n         AND hostname in('iventishirts1.com','fabrikazahranaitanci.com','soccerking-store.com','skyrecord.eu','medilinkbg.com','sotis.bg') \n      GROUP BY event_date, session_id\n  )\n  GROUP BY event_date\n)",
     "round": "0s",
     "table": "webperf_rum_events"
    }
   ]
  },
  {
   "title": "Bounce rate - Mobile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "created_at",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \n    event_date,\n    bounce_rate\nFROM (\n  SELECT\n      event_date,\n      count() AS all_sessions,\n      countIf(max_length = 1) AS bounced_sessions,\n      ((bounced_sessions / all_sessions) * 100) as bounce_rate\n  FROM\n  (\n      SELECT\n          event_date,\n          session_id,\n          max(session_length) AS max_length\n      FROM $table\n      WHERE \n        $timeFilter\n        AND event_type = 'visit_page'\n        AND visibility_state = 'visible'\n        AND device_type = 'mobile'\n        $conditionalTest(AND hostname in($hostname), $hostname)\n      GROUP BY event_date, session_id\n  )\n  GROUP BY event_date\n)\n",
     "rawQuery": "SELECT \n    event_date,\n    bounce_rate\nFROM (\n  SELECT\n      event_date,\n      count() AS all_sessions,\n      countIf(max_length = 1) AS bounced_sessions,\n      ((bounced_sessions / all_sessions) * 100) as bounce_rate\n  FROM\n  (\n      SELECT\n          event_date,\n          session_id,\n          max(session_length) AS max_length\n      FROM default.webperf_rum_events\n      WHERE \n        event_date >= toDate(1666184817) AND event_date <= toDate(1668780417) AND created_at >= toDateTime(1666184817) AND created_at <= toDateTime(1668780417)\n        AND event_type = 'visit_page'\n        AND visibility_state = 'visible'\n        AND device_type = 'mobile'\n         AND hostname in('iventishirts1.com','fabrikazahranaitanci.com','soccerking-store.com','skyrecord.eu','medilinkbg.com','sotis.bg') \n      GROUP BY event_date, session_id\n  )\n  GROUP BY event_date\n)",
     "round": "0s",
     "table": "webperf_rum_events"
    }
   ]
  },
  {
   "title": "Bounce rate - Desktop",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "created_at",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \n    event_date,\n    bounce_rate\nFROM (\n  SELECT\n      event_date,\n      count() AS all_sessions,\n      countIf(max_length = 1) AS bounced_sessions,\n      ((bounced_sessions / all_sessions) * 100) as bounce_rate\n  FROM\n  (\n      SELECT\n          event_date,\n          session_id,\n          max(session_length) AS max_length\n      FROM $table\n      WHERE \n        $timeFilter\n        AND event_type = 'visit_page'\n        AND visibility_state = 'visible'\n        AND device_type = 'desktop'\n        $conditionalTest(AND hostname in($hostname), $hostname)\n      GROUP BY event_date, session_id\n  )\n  GROUP BY event_date\n)\n",
     "rawQuery": "SELECT \n    event_date,\n    bounce_rate\nFROM (\n  SELECT\n      event_date,\n      count() AS all_sessions,\n      countIf(max_length = 1) AS bounced_sessions,\n      ((bounced_sessions / all_sessions) * 100) as bounce_rate\n  FROM\n  (\n      SELECT\n          event_date,\n          session_id,\n          max(session_length) AS max_length\n      FROM default.webperf_rum_events\n      WHERE \n        event_date >= toDate(1666184865) AND event_date <= toDate(1668780465) AND created_at >= toDateTime(1666184865) AND created_at <= toDateTime(1668780465)\n        AND event_type = 'visit_page'\n        AND visibility_state = 'visible'\n        AND device_type = 'desktop'\n         AND hostname in('iventishirts1.com','fabrikazahranaitanci.com','soccerking-store.com','skyrecord.eu','medilinkbg.com','sotis.bg') \n      GROUP BY event_date, session_id\n  )\n  GROUP BY event_date\n)",
     "round": "0s",
     "table": "webperf_rum_events"
    }
   ]
  },
  {
   "title": "Bounce rate - Tablet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "created_at",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \n    event_date,\n    bounce_rate\nFROM (\n  SELECT\n      event_date,\n      count() AS all_sessions,\n      countIf(max_length = 1) AS bounced_sessions,\n      ((bounced_sessions / all_sessions) * 100) as bounce_rate\n  FROM\n  (\n      SELECT\n          event_date,\n          session_id,\n          max(session_length) AS max_length\n      FROM $table\n      WHERE \n        $timeFilter\n        AND event_type = 'visit_page'\n        AND visibility_state = 'visible'\n        AND device_type = 'tablet'\n        $conditionalTest(AND hostname in($hostname), $hostname)\n      GROUP BY event_date, session_id\n  )\n  GROUP BY event_date\n)\n",
     "rawQuery": "SELECT \n    event_date,\n    bounce_rate\nFROM (\n  SELECT\n      event_date,\n      count() AS all_sessions,\n      countIf(max_length = 1) AS bounced_sessions,\n      ((bounced_sessions / all_sessions) * 100) as bounce_rate\n  FROM\n  (\n      SELECT\n          event_date,\n          session_id,\n          max(session_length) AS max_length\n      FROM default.webperf_rum_events\n      WHERE \n        event_date >= toDate(1666185015) AND event_date <= toDate(1668780615) AND created_at >= toDateTime(1666185015) AND created_at <= toDateTime(1668780615)\n        AND event_type = 'visit_page'\n        AND visibility_state = 'visible'\n        AND device_type = 'tablet'\n         AND hostname in('iventishirts1.com','fabrikazahranaitanci.com','soccerking-store.com','skyrecord.eu','medilinkbg.com','sotis.bg') \n      GROUP BY event_date, session_id\n  )\n  GROUP BY event_date\n)",
     "round": "0s",
     "table": "webperf_rum_events"
    }
   ]
  },
  {
   "title": "Sessions per day - All device types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "created_at",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    event_date,\n    uniq(session_id) as sessions_per_day_all\nFROM $table\nWHERE \n  $timeFilter\n  AND event_type = 'visit_page'\n  AND visibility_state = 'visible'\n  AND device_type IN ('mobile', 'desktop', 'tablet')\n  $conditionalTest(AND hostname in($hostname), $hostname)\nGROUP BY event_date\nORDER BY event_date\n\n",
     "rawQuery": "SELECT\n    event_date,\n    uniq(session_id) as sessions_per_day_all\nFROM default.webperf_rum_events\nWHERE \n  event_date >= toDate(1666184664) AND event_date <= toDate(1668780264) AND created_at >= toDateTime(1666184664) AND created_at <= toDateTime(1668780264)\n  AND event_type = 'visit_page'\n  AND visibility_state = 'visible'\n  AND device_type IN ('mobile', 'desktop', 'tablet')\n   AND hostname in('iventishirts1.com','fabrikazahranaitanci.com','soccerking-store.com','skyrecord.eu','medilinkbg.com','sotis.bg') \nGROUP BY event_date\nORDER BY event_date",
     "round": "0s",
     "table": "webperf_rum_events"
    }
   ]
  },
  {
   "title": "Sessions per day - Mobile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "created_at",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    event_date,\n    uniq(session_id) as sessions_per_day_mobile\nFROM $table\nWHERE \n  $timeFilter\n  AND event_type = 'visit_page'\n  AND visibility_state = 'visible'\n  AND device_type = 'mobile'\n  $conditionalTest(AND hostname in($hostname), $hostname)\nGROUP BY event_date\nORDER BY event_date\n\n\n",
     "rawQuery": "SELECT\n    event_date,\n    uniq(session_id) as sessions_per_day_mobile\nFROM default.webperf_rum_events\nWHERE \n  event_date >= toDate(1666184791) AND event_date <= toDate(1668780391) AND created_at >= toDateTime(1666184791) AND created_at <= toDateTime(1668780391)\n  AND event_type = 'visit_page'\n  AND visibility_state = 'visible'\n  AND device_type = 'mobile'\n   AND hostname in('iventishirts1.com','fabrikazahranaitanci.com','soccerking-store.com','skyrecord.eu','medilinkbg.com','sotis.bg') \nGROUP BY event_date\nORDER BY event_date",
     "round": "0s",
     "table": "webperf_rum_events"
    }
   ]
  },
  {
   "title": "Sessions per day - Desktop",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "created_at",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    event_date,\n    uniq(session_id) as sessions_per_day_desktop\nFROM $table\nWHERE \n  $timeFilter\n  AND event_type = 'visit_page'\n  AND visibility_state = 'visible'\n  AND device_type = 'desktop'\n  $conditionalTest(AND hostname in($hostname), $hostname)\nGROUP BY event_date\nORDER BY event_date\n\n\n",
     "rawQuery": "SELECT\n    event_date,\n    uniq(session_id) as sessions_per_day_desktop\nFROM default.webperf_rum_events\nWHERE \n  event_date >= toDate(1666184598) AND event_date <= toDate(1668780198) AND created_at >= toDateTime(1666184598) AND created_at <= toDateTime(1668780198)\n  AND event_type = 'visit_page'\n  AND visibility_state = 'visible'\n  AND device_type = 'desktop'\n   AND hostname in('skyrecord.eu') \nGROUP BY event_date\nORDER BY event_date",
     "round": "0s",
     "table": "webperf_rum_events"
    }
   ]
  },
  {
   "title": "Sessions per day - Tablet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "event_date",
     "dateTimeColDataType": "created_at",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    event_date,\n    uniq(session_id) as sessions_per_day_tablet\nFROM $table\nWHERE \n  $timeFilter\n  AND event_type = 'visit_page'\n  AND visibility_state = 'visible'\n  AND device_type = 'tablet'\n  $conditionalTest(AND hostname in($hostname), $hostname)\nGROUP BY event_date\nORDER BY event_date\n\n\n",
     "rawQuery": "SELECT\n    event_date,\n    uniq(session_id) as sessions_per_day_tablet\nFROM default.webperf_rum_events\nWHERE \n  event_date >= toDate(1666184628) AND event_date <= toDate(1668780228) AND created_at >= toDateTime(1666184628) AND created_at <= toDateTime(1668780228)\n  AND event_type = 'visit_page'\n  AND visibility_state = 'visible'\n  AND device_type = 'tablet'\n   AND hostname in('iventishirts1.com','fabrikazahranaitanci.com','soccerking-store.com','skyrecord.eu','medilinkbg.com','sotis.bg') \nGROUP BY event_date\nORDER BY event_date",
     "round": "0s",
     "table": "webperf_rum_events"
    }
   ]
  }
 ]
}