apiVersion: 1

datasources:
  - name: Altinity plugin for ClickHouse
    uid: BRUMMUCSTARBUCS
    type: vertamedia-clickhouse-datasource
    url: $CLICKHOUSE_CONNECTION_URL
    basicAuth: true
    basicAuthUser: $CLICKHOUSE_USER
    jsonData:
      tlsSkipVerify: false
    secureJsonData:
      basicAuthPassword: "$CLICKHOUSE_PASSWORD"
    secureJsonFields:
      basicAuthPassword: false
